let list = [{
  "answer": "鱼贯而入",
  "img": "images/001.png"
}, {
  "answer": "四通八达",
  "img": "images/002.png"
  }, {
    "answer": "网开一面",
    "img": "images/003.png"
  }, {
    "answer": "头重脚轻",
    "img": "images/004.png"
  }, {
    "answer": "命悬一线",
    "img": "images/005.png"
  }, {
    "answer": "鱼目混珠",
    "img": "images/006.png"
  }, {
    "answer": "水滴石穿",
    "img": "images/007.png"
  }, {
    "answer": "穷困潦倒",
    "img": "images/008.png"
  }, {
    "answer": "胆大包天",
    "img": "images/009.png"
  }, {
    "answer": "破口大骂",
    "img": "images/010.png"
  }, {
    "answer": "天外有天",
    "img": "images/011.png"
  }, {
    "answer": "表里如一",
    "img": "images/012.png"
  }, {
    "answer": "前赴后继",
    "img": "images/013.png"
  }, {
    "answer": "横冲直撞",
    "img": "images/014.png"
  }, {
    "answer": "杀鸡取卵",
    "img": "images/015.png"
  }, {
    "answer": "狗急跳墙",
    "img": "images/016.png"
  }, {
    "answer": "貌合神离",
    "img": "images/017.png"
  }, {
    "answer": "东张西望",
    "img": "images/018.png"
  }, {
    "answer": "对牛弹琴",
    "img": "images/019.png"
  }, {
    "answer": "普天同庆",
    "img": "images/020.png"
  }, {
    "answer": "半夜三更",
    "img": "images/021.png"
  }, {
    "answer": "妙手回春",
    "img": "images/022.png"
  }, {
    "answer": "百川归海",
    "img": "images/023.png"
  }, {
    "answer": "掩人耳目",
    "img": "images/024.png"
  }, {
    "answer": "指鹿为马",
    "img": "images/025.png"
  }, {
    "answer": "弹尽粮绝",
    "img": "images/026.png"
  }, {
    "answer": "沧海一栗",
    "img": "images/027.png"
  }, {
    "answer": "若隐若现",
    "img": "images/028.png"
  }, {
    "answer": "远走高飞",
    "img": "images/029.png"
  }, {
    "answer": "只手遮天",
    "img": "images/030.png"
  }, {
    "answer": "一目十行",
    "img": "images/031.png"
  }, {
    "answer": "胆小如鼠",
    "img": "images/032.png"
  }, {
    "answer": "心直口快",
    "img": "images/033.png"
  }, {
    "answer": "坐吃山空",
    "img": "images/034.png"
  }, {
    "answer": "月下老人",
    "img": "images/035.png"
  }, {
    "answer": "哭笑不得",
    "img": "images/036.png"
  }, {
    "answer": "苦中作乐",
    "img": "images/037.png"
  }, {
    "answer": "风花雪月",
    "img": "images/038.png"
  }, {
    "answer": "人面兽心",
    "img": "images/039.png"
  }, {
    "answer": "偷天换日",
    "img": "images/040.png"
  }, {
    "answer": "嫦娥奔月",
    "img": "images/041.png"
  }, {
    "answer": "狗急跳墙",
    "img": "images/042.png"
  }, {
    "answer": "三人成虎",
    "img": "images/043.png"
  }, {
    "answer": "青黄不接",
    "img": "images/044.png"
  }, {
    "answer": "德高望重",
    "img": "images/045.png"
  }, {
    "answer": "七手八脚",
    "img": "images/046.png"
  }, {
    "answer": "见钱眼开",
    "img": "images/047.png"
  }, {
    "answer": "四大皆空",
    "img": "images/048.png"
  }, {
    "answer": "如坐针毡",
    "img": "images/049.png"
  }, {
    "answer": "百里挑一",
    "img": "images/050.png"
  }, {
    "answer": "绝处逢生",
    "img": "images/051.png"
  }, {
    "answer": "开门见山",
    "img": "images/052.png"
  }, {
    "answer": "八面来风",
    "img": "images/053.png"
  }, {
    "answer": "话中有话",
    "img": "images/054.png"
  }, {
    "answer": "大跌眼镜",
    "img": "images/055.png"
  }, {
    "answer": "鸡犬升天",
    "img": "images/056.png"
  }, {
    "answer": "日上三竿",
    "img": "images/057.png"
  }, {
    "answer": "大显身手",
    "img": "images/058.png"
  }, {
    "answer": "逆水行舟",
    "img": "images/059.png"
  }, {
    "answer": "火烧眉毛",
    "img": "images/060.png"
  }, {
    "answer": "一心一意",
    "img": "images/061.png"
  }, {
    "answer": "唉声叹气",
    "img": "images/062.png"
  }, {
    "answer": "满腹经纶",
    "img": "images/063.png"
  }, {
    "answer": "妙笔生花",
    "img": "images/064.png"
  }, {
    "answer": "善男信女",
    "img": "images/065.png"
  }, {
    "answer": "三心二意",
    "img": "images/066.png"
  }, {
    "answer": "班门弄斧",
    "img": "images/067.png"
  }, {
    "answer": "名震一时",
    "img": "images/068.png"
  }, {
    "answer": "思前想后",
    "img": "images/069.png"
  }, {
    "answer": "画蛇添足",
    "img": "images/070.png"
  }, {
    "answer": "萍水相逢",
    "img": "images/071.png"
  }, {
    "answer": "不可一世",
    "img": "images/072.png"
  }, {
    "answer": "平步青云",
    "img": "images/073.png"
  }, {
    "answer": "怒火中烧",
    "img": "images/074.png"
  }, {
    "answer": "落叶知秋",
    "img": "images/075.png"
  }, {
    "answer": "颠三倒四",
    "img": "images/076.png"
  }, {
    "answer": "目中无人",
    "img": "images/077.png"
  }, {
    "answer": "锦上添花",
    "img": "images/078.png"
  }, {
    "answer": "走马观花",
    "img": "images/079.png"
  }, {
    "answer": "七零八落",
    "img": "images/080.png"
  }, {
    "answer": "甘拜下风",
    "img": "images/081.png"
  }, {
    "answer": "拨乱反正",
    "img": "images/082.png"
  }, {
    "answer": "画地为牢",
    "img": "images/083.png"
  }, {
    "answer": "一举两得",
    "img": "images/084.png"
  }, {
    "answer": "弃笔从戎",
    "img": "images/085.png"
  }, {
    "answer": "缺衣少食",
    "img": "images/086.png"
  }, {
    "answer": "一目十行",
    "img": "images/031.png"
  }, {
    "answer": "七上八下",
    "img": "images/088.png"
  }, {
    "answer": "门可罗雀",
    "img": "images/089.png"
  }, {
    "answer": "参差不齐",
    "img": "images/090.png"
  }, {
    "answer": "渐入佳境",
    "img": "images/091.png"
  }, {
    "answer": "马到成功",
    "img": "images/092.png"
  }, {
    "answer": "八仙过海",
    "img": "images/093.png"
  }, {
    "answer": "行尸走肉",
    "img": "images/094.png"
  }, {
    "answer": "披星戴月",
    "img": "images/095.png"
  }, {
    "answer": "无与伦比",
    "img": "images/096.png"
  }, {
    "answer": "两情相悦",
    "img": "images/097.png"
  }, {
    "answer": "拈花惹草",
    "img": "images/098.png"
  }, {
    "answer": "乘风破浪",
    "img": "images/099.png"
  }, {
    "answer": "立锥之地",
    "img": "images/100.png"
  }, {
    "answer": "面红耳赤",
    "img": "images/101.png"
  }, {
    "answer": "羊入虎口",
    "img": "images/102.png"
  }, {
    "answer": "引人入胜",
    "img": "images/103.png"
  }, {
    "answer": "天崩地裂",
    "img": "images/104.png"
  }, {
    "answer": "楚河汉界",
    "img": "images/105.png"
  }, {
    "answer": "一石二鸟",
    "img": "images/106.png"
  }, {
    "answer": "重蹈覆辙",
    "img": "images/107.png"
  }, {
    "answer": "成王败寇",
    "img": "images/108.png"
  }, {
    "answer": "如雷贯耳",
    "img": "images/109.png"
  }, {
    "answer": "一帆风顺",
    "img": "images/110.png"
  }, {
    "answer": "每况日下",
    "img": "images/111.png"
  }, {
    "answer": "粗茶淡饭",
    "img": "images/112.png"
  }, {
    "answer": "军令如山",
    "img": "images/113.png"
  }, {
    "answer": "小鸟依人",
    "img": "images/114.png"
  }, {
    "answer": "门当户对",
    "img": "images/115.png"
  }, {
    "answer": "日行千里",
    "img": "images/116.png"
  }, {
    "answer": "不分彼此",
    "img": "images/117.png"
  }, {
    "answer": "藕断丝连",
    "img": "images/118.png"
  }, {
    "answer": "官官相护",
    "img": "images/119.png"
  }, {
    "answer": "一叶障目",
    "img": "images/120.png"
  }, {
    "answer": "愚公移山",
    "img": "images/121.png"
  }, {
    "answer": "妙语如珠",
    "img": "images/122.png"
  }, {
    "answer": "百里挑一",
    "img": "images/123.png"
  }, {
    "answer": "目不识丁",
    "img": "images/124.png"
  }, {
    "answer": "支离破碎",
    "img": "images/125.png"
  }, {
    "answer": "全心投入",
    "img": "images/126.png"
  }, {
    "answer": "石破天惊",
    "img": "images/127.png"
  }, {
    "answer": "弥天大谎",
    "img": "images/128.png"
  }, {
    "answer": "飞黄腾达",
    "img": "images/129.png"
  }, {
    "answer": "劳燕分飞",
    "img": "images/130.png"
  }, {
    "answer": "朝三暮四",
    "img": "images/131.png"
  }, {
    "answer": "隔岸观火",
    "img": "images/132.png"
  }, {
    "answer": "卧薪尝胆",
    "img": "images/133.png"
  }, {
    "answer": "穷山恶水",
    "img": "images/134.png"
  }, {
    "answer": "废话连篇",
    "img": "images/135.png"
  }, {
    "answer": "安然无恙",
    "img": "images/136.png"
  }, {
    "answer": "无中生有",
    "img": "images/137.png"
  }, {
    "answer": "明镜高悬",
    "img": "images/138.png"
  }, {
    "answer": "无的放矢",
    "img": "images/139.png"
  }, {
    "answer": "强词夺理",
    "img": "images/140.png"
  }, {
    "answer": "厚此薄彼",
    "img": "images/141.png"
  }, {
    "answer": "近水楼台",
    "img": "images/142.png"
  }, {
    "answer": "单枪匹马",
    "img": "images/143.png"
  }, {
    "answer": "画龙点睛",
    "img": "images/144.png"
  }, {
    "answer": "七窍生烟",
    "img": "images/145.png"
  }, {
    "answer": "身怀六甲",
    "img": "images/146.png"
  }, {
    "answer": "缺衣少食",
    "img": "images/086.png"
  }, {
    "answer": "马首是瞻",
    "img": "images/148.png"
  }, {
    "answer": "泰山压顶",
    "img": "images/149.png"
  }, {
    "answer": "苦口婆心",
    "img": "images/150.png"
  }, {
    "answer": "马放南山",
    "img": "images/151.png"
  }, {
    "answer": "半壁江山",
    "img": "images/152.png"
  }, {
    "answer": "如意算盘",
    "img": "images/153.png"
  }, {
    "answer": "毛手毛脚",
    "img": "images/154.png"
  }, {
    "answer": "改朝换代",
    "img": "images/155.png"
  }, {
    "answer": "鹤立鸡群",
    "img": "images/156.png"
  }, {
    "answer": "独当一面",
    "img": "images/157.png"
  }, {
    "answer": "半截入土",
    "img": "images/158.png"
  }, {
    "answer": "满载而归",
    "img": "images/159.png"
  }, {
    "answer": "八仙过海",
    "img": "images/093.png"
  }, {
    "answer": "脱口而出",
    "img": "images/161.png"
  }, {
    "answer": "鸟语花香",
    "img": "images/162.png"
  }, {
    "answer": "一刀两断",
    "img": "images/163.png"
  }, {
    "answer": "九牛一毛",
    "img": "images/164.png"
  }, {
    "answer": "明珠暗投",
    "img": "images/165.png"
  }, {
    "answer": "人仰马翻",
    "img": "images/166.png"
  }, {
    "answer": "柳暗花明",
    "img": "images/167.png"
  }, {
    "answer": "上下其手",
    "img": "images/168.png"
  }, {
    "answer": "待字闺中",
    "img": "images/169.png"
  }, {
    "answer": "鱼目混珠",
    "img": "images/170.png"
  }, {
    "answer": "不堪回首",
    "img": "images/171.png"
  }, {
    "answer": "轰轰烈烈",
    "img": "images/172.png"
  }, {
    "answer": "大步流星",
    "img": "images/173.png"
  }, {
    "answer": "偷鸡摸狗",
    "img": "images/174.png"
  }, {
    "answer": "囊萤映雪",
    "img": "images/175.png"
  }, {
    "answer": "春色满园",
    "img": "images/184.png"
  }, {
    "answer": "颠三倒四",
    "img": "images/076.png"
  }, {
    "answer": "火上浇油",
    "img": "images/178.png"
  }, {
    "answer": "一泻千里",
    "img": "images/179.png"
  }, {
    "answer": "绿林好汉",
    "img": "images/180.png"
  }, {
    "answer": "分崩离析",
    "img": "images/181.png"
  }, {
    "answer": "逆水行舟",
    "img": "images/059.png"
  }, {
    "answer": "浑水摸鱼",
    "img": "images/183.png"
  }, {
    "answer": "春色满园",
    "img": "images/184.png"
  }, {
    "answer": "白日做梦",
    "img": "images/185.png"
  }, {
    "answer": "大材小用",
    "img": "images/186.png"
  }, {
    "answer": "名利双收",
    "img": "images/187.png"
  }, {
    "answer": "无独有偶",
    "img": "images/188.png"
  }, {
    "answer": "无时无刻",
    "img": "images/189.png"
  }, {
    "answer": "背道而驰",
    "img": "images/190.png"
  }, {
    "answer": "老马识途",
    "img": "images/191.png"
  }, {
    "answer": "洞房花烛",
    "img": "images/192.png"
  }, {
    "answer": "凤毛麟角",
    "img": "images/193.png"
  }, {
    "answer": "爱屋及乌",
    "img": "images/194.png"
  }, {
    "answer": "天方夜谭",
    "img": "images/195.png"
  }, {
    "answer": "柳暗花明",
    "img": "images/167.png"
  }, {
    "answer": "两败俱伤",
    "img": "images/197.png"
  }, {
    "answer": "灯红酒绿",
    "img": "images/198.png"
  }, {
    "answer": "眉来眼去",
    "img": "images/199.png"
  }, {
    "answer": "玉树临风",
    "img": "images/200.png"
  }, {
    "answer": "泥牛入海",
    "img": "images/201.png"
  }, {
    "answer": "青面獠牙",
    "img": "images/202.png"
  }, {
    "answer": "里应外合",
    "img": "images/203.png"
  }, {
    "answer": "模棱两可",
    "img": "images/204.png"
  }, {
    "answer": "人去楼空",
    "img": "images/205.png"
  }, {
    "answer": "草木皆兵",
    "img": "images/206.png"
  }, {
    "answer": "浪子回头",
    "img": "images/207.png"
  }, {
    "answer": "人满为患",
    "img": "images/208.png"
  }, {
    "answer": "牛鬼蛇神",
    "img": "images/209.png"
  }, {
    "answer": "面黄肌瘦",
    "img": "images/210.png"
  }, {
    "answer": "如虎添翼",
    "img": "images/211.png"
  }, {
    "answer": "绕梁三日",
    "img": "images/212.png"
  }, {
    "answer": "充耳不闻",
    "img": "images/213.png"
  }, {
    "answer": "火冒三丈",
    "img": "images/214.png"
  }, {
    "answer": "三姑六婆",
    "img": "images/215.png"
  }, {
    "answer": "南辕北辙",
    "img": "images/216.png"
  }, {
    "answer": "相濡以沫",
    "img": "images/217.png"
  }, {
    "answer": "三心二意",
    "img": "images/066.png"
  }, {
    "answer": "水到渠成",
    "img": "images/219.png"
  }, {
    "answer": "飞蛾扑火",
    "img": "images/220.png"
  }, {
    "answer": "一五一十",
    "img": "images/221.png"
  }, {
    "answer": "水天一色",
    "img": "images/222.png"
  }, {
    "answer": "眉飞色舞",
    "img": "images/223.png"
  }, {
    "answer": "昂首挺胸",
    "img": "images/224.png"
  }, {
    "answer": "长吁短叹",
    "img": "images/225.png"
  }, {
    "answer": "并驾齐驱",
    "img": "images/226.png"
  }, {
    "answer": "指鹿为马",
    "img": "images/025.png"
  }, {
    "answer": "三足鼎立",
    "img": "images/228.png"
  }, {
    "answer": "形影不离",
    "img": "images/229.png"
  }, {
    "answer": "积少成多",
    "img": "images/230.png"
  }, {
    "answer": "声东击西",
    "img": "images/231.png"
  }, {
    "answer": "深不可测",
    "img": "images/232.png"
  }, {
    "answer": "颠三倒四",
    "img": "images/076.png"
  }, {
    "answer": "画蛇添足",
    "img": "images/234.png"
  }, {
    "answer": "买椟还珠",
    "img": "images/235.png"
  }, {
    "answer": "明枪暗箭",
    "img": "images/236.png"
  }, {
    "answer": "瓜田李下",
    "img": "images/237.png"
  }, {
    "answer": "猴子捞月",
    "img": "images/238.png"
  }, {
    "answer": "生死存亡",
    "img": "images/239.png"
  }, {
    "answer": "居高临下",
    "img": "images/240.png"
  }, {
    "answer": "是非不分",
    "img": "images/241.png"
  }, {
    "answer": "茅塞顿开",
    "img": "images/242.png"
  }, {
    "answer": "井底之蛙",
    "img": "images/243.png"
  }, {
    "answer": "雕虫小技",
    "img": "images/244.png"
  }, {
    "answer": "四脚朝天",
    "img": "images/245.png"
  }, {
    "answer": "鬼话连篇",
    "img": "images/246.png"
  }, {
    "answer": "百年树人",
    "img": "images/247.png"
  }, {
    "answer": "扬眉吐气",
    "img": "images/248.png"
  }, {
    "answer": "门可罗雀",
    "img": "images/249.png"
  }, {
    "answer": "滥竽充数",
    "img": "images/250.png"
  }, {
    "answer": "能屈能伸",
    "img": "images/251.png"
  }, {
    "answer": "骑虎难下",
    "img": "images/252.png"
  }, {
    "answer": "白纸黑字",
    "img": "images/253.png"
  }, {
    "answer": "血口喷人",
    "img": "images/254.png"
  }, {
    "answer": "肝肠寸断",
    "img": "images/255.png"
  }, {
    "answer": "群龙无首",
    "img": "images/256.png"
  }, {
    "answer": "吃里扒外",
    "img": "images/257.png"
  }, {
    "answer": "将心比心",
    "img": "images/258.png"
  }, {
    "answer": "九牛二虎",
    "img": "images/259.png"
  }, {
    "answer": "覆水难收",
    "img": "images/260.png"
  }, {
    "answer": "堆积成山",
    "img": "images/261.png"
  }, {
    "answer": "左右为难",
    "img": "images/262.png"
  }, {
    "answer": "愁眉苦脸",
    "img": "images/263.png"
  }, {
    "answer": "贼喊捉贼",
    "img": "images/264.png"
  }, {
    "answer": "五音不全",
    "img": "images/265.png"
  }, {
    "answer": "来历不明",
    "img": "images/266.png"
  }, {
    "answer": "披星戴月",
    "img": "images/267.png"
  }, {
    "answer": "如虎添翼",
    "img": "images/268.png"
  }, {
    "answer": "恩重如山",
    "img": "images/269.png"
  }, {
    "answer": "家徒四壁",
    "img": "images/270.png"
  }, {
    "answer": "无中生有",
    "img": "images/137.png"
  }, {
    "answer": "退避三舍",
    "img": "images/272.png"
  }, {
    "answer": "轻于鸿毛",
    "img": "images/273.png"
  }, {
    "answer": "拍案叫绝",
    "img": "images/274.png"
  }, {
    "answer": "两面三刀",
    "img": "images/275.png"
  }, {
    "answer": "入木三分",
    "img": "images/276.png"
  }, {
    "answer": "高高在上",
    "img": "images/277.png"
  }, {
    "answer": "鸡飞狗跳",
    "img": "images/278.png"
  }, {
    "answer": "三长两短",
    "img": "images/279.png"
  }, {
    "answer": "兵临城下",
    "img": "images/280.png"
  }, {
    "answer": "顶天立地",
    "img": "images/281.png"
  }, {
    "answer": "捧腹大笑",
    "img": "images/282.png"
  }, {
    "answer": "狗尾续貂",
    "img": "images/283.png"
  }, {
    "answer": "高山流水",
    "img": "images/284.png"
  }, {
    "answer": "功德圆满",
    "img": "images/285.png"
  }, {
    "answer": "巧言如簧",
    "img": "images/286.png"
  }, {
    "answer": "风和日丽",
    "img": "images/287.png"
  }, {
    "answer": "口是心非",
    "img": "images/288.png"
  }, {
    "answer": "井底之蛙",
    "img": "images/243.png"
  }, {
    "answer": "旗开得胜",
    "img": "images/290.png"
  }, {
    "answer": "七上八下",
    "img": "images/291.png"
  }, {
    "answer": "漏网之鱼",
    "img": "images/292.png"
  }, {
    "answer": "地广人稀",
    "img": "images/293.png"
  }, {
    "answer": "金鸡独立",
    "img": "images/294.png"
  }, {
    "answer": "天各一方",
    "img": "images/295.png"
  }, {
    "answer": "顶天立地",
    "img": "images/296.png"
  }, {
    "answer": "不堪入目",
    "img": "images/297.png"
  }, {
    "answer": "岂有此理",
    "img": "images/298.png"
  }, {
    "answer": "回头是岸",
    "img": "images/299.png"
  }, {
    "answer": "抛砖引玉",
    "img": "images/300.png"
  }, {
    "answer": "石沉大海",
    "img": "images/301.png"
  }, {
    "answer": "势如破竹",
    "img": "images/302.png"
  }, {
    "answer": "五体投地",
    "img": "images/303.png"
  }, {
    "answer": "妙笔生花",
    "img": "images/304.png"
  }, {
    "answer": "背井离乡",
    "img": "images/305.png"
  }, {
    "answer": "鸡毛蒜皮",
    "img": "images/306.png"
  }, {
    "answer": "平分秋色",
    "img": "images/307.png"
  }, {
    "answer": "多此一举",
    "img": "images/308.png"
  }, {
    "answer": "一刀两断",
    "img": "images/163.png"
  }, {
    "answer": "血肉模糊",
    "img": "images/310.png"
  }, {
    "answer": "粗心大意",
    "img": "images/311.png"
  }, {
    "answer": "跳梁小丑",
    "img": "images/312.png"
  }, {
    "answer": "目瞪口呆",
    "img": "images/313.png"
  }, {
    "answer": "俯首称臣",
    "img": "images/314.png"
  }, {
    "answer": "胸有成竹",
    "img": "images/315.png"
  }, {
    "answer": "卖国求荣",
    "img": "images/316.png"
  }, {
    "answer": "纸上谈兵",
    "img": "images/317.png"
  }, {
    "answer": "五花八门",
    "img": "images/318.png"
  }, {
    "answer": "倾国倾城",
    "img": "images/319.png"
  }, {
    "answer": "金蝉脱壳",
    "img": "images/320.png"
  }, {
    "answer": "放虎归山",
    "img": "images/321.png"
  }, {
    "answer": "东山再起",
    "img": "images/322.png"
  }, {
    "answer": "滥竽充数",
    "img": "images/250.png"
  }, {
    "answer": "三从四德",
    "img": "images/324.png"
  }, {
    "answer": "迫在眉睫",
    "img": "images/325.png"
  }, {
    "answer": "破门而入",
    "img": "images/326.png"
  }, {
    "answer": "紫气东来",
    "img": "images/327.png"
  }, {
    "answer": "明争暗斗",
    "img": "images/328.png"
  }, {
    "answer": "畏首畏尾",
    "img": "images/329.png"
  }, {
    "answer": "天下为公",
    "img": "images/330.png"
  }, {
    "answer": "拨云见日",
    "img": "images/331.png"
  }, {
    "answer": "不卑不亢",
    "img": "images/332.png"
  }, {
    "answer": "旁门左道",
    "img": "images/333.png"
  }, {
    "answer": "双管齐下",
    "img": "images/334.png"
  }, {
    "answer": "有眼无珠",
    "img": "images/335.png"
  }, {
    "answer": "抱头鼠窜",
    "img": "images/336.png"
  }, {
    "answer": "三长两短",
    "img": "images/279.png"
  }, {
    "answer": "事半功倍",
    "img": "images/338.png"
  }, {
    "answer": "一塌糊涂",
    "img": "images/339.png"
  }, {
    "answer": "一心一意",
    "img": "images/340.png"
  }, {
    "answer": "风雨交加",
    "img": "images/341.png"
  }, {
    "answer": "思如泉涌",
    "img": "images/342.png"
  }, {
    "answer": "万念俱灰",
    "img": "images/343.png"
  }, {
    "answer": "乌合之众",
    "img": "images/344.png"
  }, {
    "answer": "心花怒放",
    "img": "images/345.png"
  }, {
    "answer": "衣食父母",
    "img": "images/346.png"
  }, {
    "answer": "颠倒黑白",
    "img": "images/347.png"
  }, {
    "answer": "力争上游",
    "img": "images/348.png"
  }, {
    "answer": "五光十色",
    "img": "images/349.png"
  }, {
    "answer": "水落石出",
    "img": "images/350.png"
  }, {
    "answer": "画蛇添足",
    "img": "images/234.png"
  }, {
    "answer": "异曲同工",
    "img": "images/352.png"
  }, {
    "answer": "狼狈为奸",
    "img": "images/353.png"
  }, {
    "answer": "顺手牵羊",
    "img": "images/354.png"
  }, {
    "answer": "举手投足",
    "img": "images/355.png"
  }, {
    "answer": "抛砖引玉",
    "img": "images/300.png"
  }, {
    "answer": "排山倒海",
    "img": "images/357.png"
  }, {
    "answer": "手到病除",
    "img": "images/358.png"
  }, {
    "answer": "嗤之以鼻",
    "img": "images/359.png"
  }, {
    "answer": "才高八斗",
    "img": "images/360.png"
  }, {
    "answer": "世代相传",
    "img": "images/361.png"
  }, {
    "answer": "火烧眉毛",
    "img": "images/362.png"
  }, {
    "answer": "难以置信",
    "img": "images/363.png"
  }, {
    "answer": "才子佳人",
    "img": "images/364.png"
  }, {
    "answer": "开门见山",
    "img": "images/052.png"
  }, {
    "answer": "门庭若市",
    "img": "images/366.png"
  }, {
    "answer": "芒刺在身",
    "img": "images/367.png"
  }, {
    "answer": "出口成章",
    "img": "images/368.png"
  }, {
    "answer": "外强中干",
    "img": "images/369.png"
  }, {
    "answer": "打草惊蛇",
    "img": "images/370.png"
  }, {
    "answer": "皮开肉绽",
    "img": "images/371.png"
  }, {
    "answer": "束之高阁",
    "img": "images/372.png"
  }, {
    "answer": "病从口入",
    "img": "images/373.png"
  }, {
    "answer": "是非曲直",
    "img": "images/374.png"
  }, {
    "answer": "金屋藏娇",
    "img": "images/375.png"
  }, {
    "answer": "马失前蹄",
    "img": "images/376.png"
  }, {
    "answer": "物以类聚",
    "img": "images/377.png"
  }, {
    "answer": "夸父逐日",
    "img": "images/378.png"
  }, {
    "answer": "开卷有益",
    "img": "images/379.png"
  }, {
    "answer": "旁门左道",
    "img": "images/333.png"
  }, {
    "answer": "左右开弓",
    "img": "images/381.png"
  }, {
    "answer": "归心似箭",
    "img": "images/382.png"
  }, {
    "answer": "如雷贯耳",
    "img": "images/109.png"
  }, {
    "answer": "悬崖勒马",
    "img": "images/384.png"
  }, {
    "answer": "崇山峻岭",
    "img": "images/385.png"
  }, {
    "answer": "花前月下",
    "img": "images/386.png"
  }, {
    "answer": "比翼双飞",
    "img": "images/387.png"
  }, {
    "answer": "梁上君子",
    "img": "images/388.png"
  }, {
    "answer": "笑里藏刀",
    "img": "images/389.png"
  }, {
    "answer": "隔靴搔痒",
    "img": "images/390.png"
  }, {
    "answer": "丢三落四",
    "img": "images/391.png"
  }, {
    "answer": "箭在弦上",
    "img": "images/392.png"
  }, {
    "answer": "风和日丽",
    "img": "images/287.png"
  }, {
    "answer": "灯红酒绿",
    "img": "images/394.png"
  }, {
    "answer": "环肥燕瘦",
    "img": "images/395.png"
  }, {
    "answer": "画地为牢",
    "img": "images/396.png"
  }, {
    "answer": "僧多粥少",
    "img": "images/397.png"
  }, {
    "answer": "不可思议",
    "img": "images/398.png"
  }, {
    "answer": "半推半就",
    "img": "images/399.png"
  }, {
    "answer": "先礼后兵",
    "img": "images/400.png"
  }, {
    "answer": "蠢蠢欲动",
    "img": "images/401.png"
  }, {
    "answer": "望而生畏",
    "img": "images/402.png"
  }, {
    "answer": "无穷无尽",
    "img": "images/403.png"
  }, {
    "answer": "亡齿寒",
    "img": "images/404.png"
  }, {
    "answer": "独树一帜",
    "img": "images/405.png"
  }, {
    "answer": "酸甜苦辣",
    "img": "images/406.png"
  }, {
    "answer": "双管齐下",
    "img": "images/334.png"
  }, {
    "answer": "弱不禁风",
    "img": "images/408.png"
  }, {
    "answer": "背水一战",
    "img": "images/409.png"
  }, {
    "answer": "本末倒置",
    "img": "images/410.png"
  }, {
    "answer": "借酒浇愁",
    "img": "images/411.png"
  }, {
    "answer": "身首异处",
    "img": "images/412.png"
  }, {
    "answer": "自圆其说",
    "img": "images/413.png"
  }, {
    "answer": "妻离子散",
    "img": "images/414.png"
  }, {
    "answer": "觥筹交错",
    "img": "images/415.png"
  }, {
    "answer": "言外之意",
    "img": "images/416.png"
  }, {
    "answer": "残羹剩饭",
    "img": "images/417.png"
  }, {
    "answer": "同床异梦",
    "img": "images/418.png"
  }, {
    "answer": "毛手毛脚",
    "img": "images/419.png"
  }, {
    "answer": "风卷残云",
    "img": "images/420.png"
  }, {
    "answer": "一心一意",
    "img": "images/421.png"
  }, {
    "answer": "立竿见影",
    "img": "images/422.png"
  }, {
    "answer": "三言两语",
    "img": "images/423.png"
  }, {
    "answer": "石沉大海",
    "img": "images/424.png"
  }, {
    "answer": "三缄其口",
    "img": "images/425.png"
  }, {
    "answer": "拔苗助长",
    "img": "images/426.png"
  }, {
    "answer": "山高水长",
    "img": "images/427.png"
  }, {
    "answer": "呆若木鸡",
    "img": "images/428.png"
  }, {
    "answer": "正中下怀",
    "img": "images/429.png"
  }, {
    "answer": "水乳交融",
    "img": "images/430.png"
  }, {
    "answer": "旗开得胜",
    "img": "images/290.png"
  }, {
    "answer": "莫名其妙",
    "img": "images/432.png"
  }, {
    "answer": "盲人摸象",
    "img": "images/433.png"
  }, {
    "answer": "三六九等",
    "img": "images/434.png"
  }, {
    "answer": "山盟海誓",
    "img": "images/435.png"
  }, {
    "answer": "虎头蛇尾",
    "img": "images/436.png"
  }, {
    "answer": "死不瞑目",
    "img": "images/437.png"
  }, {
    "answer": "大惊失色",
    "img": "images/438.png"
  }, {
    "answer": "狭路相逢",
    "img": "images/439.png"
  }, {
    "answer": "闭门思过",
    "img": "images/440.png"
  }, {
    "answer": "百步穿杨",
    "img": "images/441.png"
  }, {
    "answer": "天衣无缝",
    "img": "images/442.png"
  }, {
    "answer": "屈指可数",
    "img": "images/443.png"
  }, {
    "answer": "化整为零",
    "img": "images/444.png"
  }, {
    "answer": "上下其手",
    "img": "images/445.png"
  }, {
    "answer": "九牛二虎",
    "img": "images/446.png"
  }, {
    "answer": "天下太平",
    "img": "images/447.png"
  }, {
    "answer": "度日如年",
    "img": "images/448.png"
  }, {
    "answer": "步步为营",
    "img": "images/449.png"
  }, {
    "answer": "一路顺风",
    "img": "images/450.png"
  }, {
    "answer": "粗茶淡饭",
    "img": "images/451.png"
  }, {
    "answer": "外圆内方",
    "img": "images/452.png"
  }, {
    "answer": "黑白分明",
    "img": "images/453.png"
  }, {
    "answer": "不痛不痒",
    "img": "images/454.png"
  }, {
    "answer": "想入非非",
    "img": "images/455.png"
  }, {
    "answer": "百里挑一",
    "img": "images/456.png"
  }, {
    "answer": "阴差阳错",
    "img": "images/457.png"
  }, {
    "answer": "牛头马面",
    "img": "images/458.png"
  }, {
    "answer": "四平八稳",
    "img": "images/459.png"
  }, {
    "answer": "气吞山河",
    "img": "images/460.png"
  }, {
    "answer": "姹紫嫣红",
    "img": "images/461.png"
  }, {
    "answer": "针锋相对",
    "img": "images/462.png"
  }, {
    "answer": "水落石出",
    "img": "images/350.png"
  }, {
    "answer": "千军万马",
    "img": "images/464.png"
  }, {
    "answer": "三头六臂",
    "img": "images/465.png"
  }, {
    "answer": "遁入空门",
    "img": "images/466.png"
  }, {
    "answer": "一石二鸟",
    "img": "images/467.png"
  }, {
    "answer": "杯水车薪",
    "img": "images/468.png"
  }, {
    "answer": "鞍前马后",
    "img": "images/469.png"
  }, {
    "answer": "接二连三",
    "img": "images/470.png"
  }, {
    "answer": "乘人不备",
    "img": "images/471.png"
  }, {
    "answer": "爱恨分明",
    "img": "images/472.png"
  }, {
    "answer": "三五成群",
    "img": "images/473.png"
  }, {
    "answer": "请君入瓮",
    "img": "images/474.png"
  }, {
    "answer": "雪上加霜",
    "img": "images/475.png"
  }, {
    "answer": "苟延残喘",
    "img": "images/476.png"
  }, {
    "answer": "开膛破肚",
    "img": "images/477.png"
  }, {
    "answer": "心头大患",
    "img": "images/478.png"
  }, {
    "answer": "点到为止",
    "img": "images/479.png"
  }, {
    "answer": "一刀两断",
    "img": "images/480.png"
  }, {
    "answer": "可圈可点",
    "img": "images/481.png"
  }, {
    "answer": "妙笔生花",
    "img": "images/482.png"
  }, {
    "answer": "水落石出",
    "img": "images/483.png"
  }, {
    "answer": "独出心裁",
    "img": "images/484.png"
  }, {
    "answer": "十分好笑",
    "img": "images/485.png"
  }, {
    "answer": "无中生有",
    "img": "images/486.png"
  }, {
    "answer": "老牛舐犊",
    "img": "images/487.png"
  }, {
    "answer": "春色满园",
    "img": "images/488.png"
  }, {
    "answer": "日上三竿",
    "img": "images/057.png"
  }, {
    "answer": "滥竽充数",
    "img": "images/250.png"
  }, {
    "answer": "安身立命",
    "img": "images/491.png"
  }, {
    "answer": "昂首阔步",
    "img": "images/492.png"
  }, {
    "answer": "仗势欺人",
    "img": "images/493.png"
  }, {
    "answer": "断子绝孙",
    "img": "images/494.png"
  }, {
    "answer": "见缝插针",
    "img": "images/495.png"
  }, {
    "answer": "危在旦夕",
    "img": "images/496.png"
  }, {
    "answer": "拔苗助长",
    "img": "images/426.png"
  }, {
    "answer": "窃窃私语",
    "img": "images/498.png"
  }, {
    "answer": "旗开得胜",
    "img": "images/290.png"
  }, {
    "answer": "柳暗花明",
    "img": "images/167.png"
  }]
module.exports = {
  list: list
  // usedraw: usedraw
}